// Code generated by go generate DO NOT EDIT.

package model

import "github.com/react/next-sample/backend/domain/entity"

// ORM モデルを Entity に変換
func (dbRecipe *Recipe) ToEntity() *entity.Recipe {

	entityRecipeMaterial := make([]entity.RecipeMaterial, len(dbRecipe.RecipeMaterials))
	for i, tmpData := range dbRecipe.RecipeMaterials {
		entityRecipeMaterial[i] = *tmpData.ToEntity()
	}
	return &entity.Recipe{
		Id:              dbRecipe.Id,
		Title:           dbRecipe.Title,
		Content:         dbRecipe.Content,
		Image:           dbRecipe.Image,
		CreatedAt:       dbRecipe.CreatedAt,
		UpdatedAt:       dbRecipe.UpdatedAt,
		RecipeMaterials: entityRecipeMaterial,
	}
}

func ToRecipeMapper(entity *entity.Recipe) *Recipe {
	return &Recipe{
		Id:        entity.Id,
		Title:     entity.Title,
		Content:   entity.Content,
		Image:     entity.Image,
		CreatedAt: entity.CreatedAt,
		UpdatedAt: entity.UpdatedAt,
	}
}
