// Code generated by go generate DO NOT EDIT.

package model

import "github.com/react/next-sample/backend/domain/entity"

// ORM モデルを Entity に変換
func (dbRecipeMaterial *RecipeMaterial) ToEntity() *entity.RecipeMaterial {

	return &entity.RecipeMaterial{
		Id:        dbRecipeMaterial.Id,
		RecipeId:  dbRecipeMaterial.RecipeId,
		Name:      dbRecipeMaterial.Name,
		CreatedAt: dbRecipeMaterial.CreatedAt,
		UpdatedAt: dbRecipeMaterial.UpdatedAt,
	}
}

func ToRecipeMaterialMapper(entity *entity.RecipeMaterial) *RecipeMaterial {
	return &RecipeMaterial{
		Id:        entity.Id,
		RecipeId:  entity.RecipeId,
		Name:      entity.Name,
		CreatedAt: entity.CreatedAt,
		UpdatedAt: entity.UpdatedAt,
	}
}
