// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xXW28bRRT+K6sDEi9b7zqlSOwbiApFIIFCgQccVZPdE3ui3dnt7GxVy7IUrwuJclFC",
	"VFIFBSpBVCNKKwQPNJSWHzO14/4LNHux117nJp6QeEnGcznznW++881sC2zfC3yGTIRgtQDvEC9wMWlH",
	"DO8EaAt0biLnPld9YeR5hDfBgk9Ho1o6qsNt4kYIFrRqTNNqYPsO1sDSanB9YeFt0zTnaqCnQx6GIaln",
	"o5+jZvuR67A3hNYgzHFRa/oR1zjeijAUlRrUWBvabR1Cu4EeScAtoE0DVK2A+wFyQVPQts8EMqGaDoY2",
	"p4GgPgMLXj4/lPHGYP9YxnvXTHOwv9Z/fF92XshOb/jT4/6Tb2WnJzvbSc8B6DkTYEG1cnLwfLhzKOO9",
	"Vz8+kJ1jGd+VnQPZuds/Spd8IzuP+utrMt6s1djcePpw61hFjTdBB9FUcCEUnLI6tHWwORLFLUnALvvc",
	"Uy1wiMArgno4aw11yonJ7i8y/kN2782/NwF7sn8UnzLx1pvj2JQJrCNPgnukjgURFGOc3HvW7+7I7tcy",
	"Pp4FzCMCOSVuWMY3OFztH/WqZn91U3aeDL7bHewfyHivei0/gt5ga+0M/r+AlE/QQXbXZfd72V1X7c62",
	"jL+Una9kvAGLOlCBXrJ7CVvWQTgnzeQ3FS6ewaOM/5bxUbLXIxnvzZkXBDqO0N/dnkVSFDiXPPG2DqoK",
	"KEdHEUEdyOEXKddHqs8PcUJdExsvjvbwl1bQFgpXWksf0lCU68nNekf0vs5xGSx4zRgbh5HVpZEV5QzO",
	"g0xaZdUFyG+ePip8Qdybth+lJT09YYqf4uxC5Gx7PU1mFgMjf5s2EwcnjooycXVuZvFkjjZDgFMYk5jj",
	"+WU0agFly34SKpUqLFz/5Ib2zsfzymSRh6lgzYpZqaq9/QAZCShYcLViVq4m+YpGkoGh/tQxIU9lRpTY",
	"5x2w4H0Un2WhFMAw8FmYZj1nmuXq+OiD1IFH/i+7u7L7l4yfym5Pdn8/+eHP4c+J6kk9VHnmOBfVMoMn",
	"yjByNZ2GqKBElQQnHgrkKl4LqIJxK0LeBB0Y8RQv2bmm+ktBL5PIFWBVdfAoo17kJe2ScBZnJ124PkgQ",
	"uNRO4BkroSKhVdjoEvWQpFOqCUXLlFGu7/Y3HpRozjzl5dPV4cNef2e//+J+geaU2EmWOdZpKDAVtB/O",
	"oHohm5EVbKpQDMW7vtOcosGLXEEDwoWhquCKQ0SSPzLbd5S+VXnQ1E+zVTcyrpUTGQGr61raXAmwXrjG",
	"/8t3d57xJMwkTU2NacLXllCLAtcnDjrF+3eJMpJI+P879PJ36LTfn3EVzjbW8WrBI2yXTKB6Aecb7P86",
	"fLgzfhodPHu19ds5JdlK/8877fPtr2x9pz74ZLyX8qlufpYYomiM7THfFKYTL9bguS/Df+2VF3kynG6H",
	"+tjUz93zvM+XWUjyNUZpwaRXnZVFPr+URDT9lXSKu5/h62oB8tu5FiLuggUNIQLLMFzfJm7DD4Wlvq9A",
	"nVQWoDWpAWjro578Zm4vtv8JAAD//2DGT5T/DQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
