// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xXXW/cRBf+K9Z5X4kbN3ZSioTvQFQoAgmUFrhgo2pqn+xOZY/d8bhqtFqpaxca+qGE",
	"qKQKClQqURdRWhAg0VBafsx0N9t/gcYfu+u1s9sIcVGJm2R2Ps485znPOWfcBtv3Ap8hEyFYbcDLxAtc",
	"TMcRw8sB2gKdc8i5z9VcGHke4etgwUejVS1b1eEScSMEC9oNpmkNsH0HG2BpDTi9svKmaZpLDdCzJQ/D",
	"kDTz1U9Qs/3IddhrQmsR5riorfsR1zhejDAUCw1osA50OjqEdgs9koJbQZsGqEYB9wPkgmagbZ8JZEIN",
	"HQxtTgNBfQYWPH+6J+Prg50DGW+fMs3BzrX+wzuy+0x2e8PvH/YffS27Pdm9lc7sgl4wARYsLhzuPh1u",
	"7sl4+8V3d2X3QMZXZXdXdq/297MjX8nug/7GNRnfaDTY0nj78OaBshrfAB3EuoILoeCUNaGjg82RKG5J",
	"CnbN554agUMEnhDUw7oz1Kk6JpMfZfy7TG4vv1OCXZ4f2adMvPH62DZlApvIU+MeaeKECCZtHN5+0k82",
	"ZfKljA/qgHlEIKfEDav4BntX+vu9RbN/5YbsPhp8szXY2ZXx9uKpIgS9wc1rM/j/FDI+QQeZbMjkW5ls",
	"qHH3low/k93PZXwdVnWgAr309gq2fIJwTtbT31S4OINHGf8l4/30rgcy3l4yXxLo2EJ/61YdSVHgHDPi",
	"HR1UFlCOjiKCOlDAn6RcH6m+CGJJXaWLV0d3+OcvoC0UriyX3qehqOaTm8+O6P0/xzWw4H/GuHAYeV4a",
	"eVLWcB7k0qqqLkB+7uhV4QvinrP9KEvp6Q1T/EzunrCcX69nztQxMKpv08XEwVKoKBMnl2qTJ69oNQKc",
	"wpjaHO+volEHKFvzU1OZVGHl9Jmz2lsfLqsiizzMBGsumAuL6m4/QEYCChacXDAXTqb+ilbqgaH+NDEl",
	"T3lGlNiXHbDgXRQf56YUwDDwWZh5vWSa1ez44L2sAo/qv0y2ZPKnjB/LpCeTXw/v/TH8IVU9aYbKzwLn",
	"qjpm8FQZRqGmoxBNKFE5wYmHArmy1waqYFyMkK+DDox4ipc8rpn+MtBrJHIFWIs6eJRRL/LScUU4q/VO",
	"T7QPEgQutVN4xoVQkdCeuOgY+ZC6U8kJRctUodzY6l+/W6E5rynPH18Z3u/1N3f6z+5M0JwRW2aZY5OG",
	"AjNB+2EN1Sv5jjxhM4ViKN72nfUpGrzIFTQgXBgqC044RKT+I7N9R+lbpQfN6ml+6mzOtapERsCaupYN",
	"LwTYnGjjr3LvLjwuw0zd1NSaJnztPGpR4PrEQWey/56njKQS/q+HHr+HTtf7Ga2wvrCOTwseYadSBBZf",
	"ovINdn4e3t8cP412n7y4+cuclAyRcLs1v/Sdyfb9y8VPrzd4EaYJKlsvKXJ/7/C3ezL5STWB5ItSDKtr",
	"02F85apv5tKcILez/8tOZ36gqyE+8lUv4+0sadTzjqWBF61x1IpLZwZv7vP/H4fkZd6FR7Ouj8U79855",
	"36h1SIozRuVAuSHN8qLYX3Eimv4UPkJEM5q3OoD8UqGFiLtgQUuIwDIM17eJ2/JDYamPaFCRyg20yxoA",
	"ldj5TPH86qx2/g4AAP//IEEYs+QPAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
