// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RWX28bRRD/KtaAxMthnxOKxL2BqFAEEij8e8BRtNxNnK3ubq97e1Uty1LuXEiUP0oU",
	"QaqgQCWIakRpheCBBmj5MFs77rdAe3tnn31OnAr1JVnv7sz85je/mds22MwLmI++CMFqA94mXuBiuo58",
	"vB2gLdBZRc4ZV3th5HmEt8CCT0enFX1qwC3iRggWtBt+pdIAmznYAKvSgOvLy2+ZprnQAEMfeRiGpJmd",
	"fo4Vm0Wu478mKuvEd1ystFjEKxxvRhiKagMafgc6HQNCex09koJbRpsGqFYBZwFyQTVom/kCfaGWDoY2",
	"p4GgzAcLnj05kcn24OhMJofXTHNwtNl/eFfGT2XcG/78sP/oOxn3ZLyX7hyDkTMBFtSr58dPhvsnMjl8",
	"/tM9GZ/J5I6Mj2V8p3+qTb6V8YP+1qZMdhoNf2F8fbh7prwmO2CAaCm4EApO/SZ0DLA5EsUtScGuMe6p",
	"FThE4OuCejjLhjrlxGT3V5n8KbvfLL07AXtyf+Sf+uLNN8a+qS+wiVw594hATokblmMMTjb6p7262d/Y",
	"kfGjwfcHg6NjmRzWr+U09ga7m5dw+AVoTsAA2d2S3R9kd0ut4z2ZfCXjr2WyDSsGUIFeGr2UeLZBOCet",
	"9DcVLl7ChUz+lclpGuuBTA4XzCsCHXvoH+zNqkAUOC9YtY4BSsmUo6OIoA7k8IuUGyPlTihjIuDKyDf7",
	"8gbaQuHRffABDUW5F9xsd0TrqxzXwIJXauOmr2U9VcsaagbXAWlioSgFxQTIVy8+FUwQd9VmkW7H6QtT",
	"vBRvFzxn4Q2dzCwGRrNpehA4OFEi6ovFhdnC19NohvCmMKY+x/fLaJQB9ddY6kpLFJavf/xJ5e2PltSA",
	"RB5qoZpVs1pXsVmAPgkoWLBYNauLab5iPc2gpv40MSVPZUaUyJccsOA9FJ9lrhTAMGB+qLNeMM1yV3z4",
	"vp6eo9ktuwey+49MHstuT3b/OP/xr+EvqdpJM1R55jhXlFmNp8qo5Wq6CFFBiSoJTjwUyJW/NlAF42aE",
	"vAUG+MRTvGR11frToNdI5Aqw6gZ41Kde5KXrknBWZiddGP0kCFxqp/BqN0JFQrsQ6AX6IU2n1BOKlqkB",
	"uXXQ375XojmbJc8ebwzv9/r7R/2ndws0a2InWebYpKFALWgWzqB6ObuRNaxWKIbiHea0XhYNBQrGUu+U",
	"ylC/gvYGR78N7++PqDk//vv57u9zSGnr/0tOZ74Ay+K78HMpk0P9NQBDK1S13ligeVAoDgHBIyyKdu53",
	"9X+r9SrVuViQxrit5sac9/ibhSS3qZUMxg+2eVnk90tJRNNvzAv665LOUgbIb+VaiLgLFqwLEVi1msts",
	"4q6zUFjqdQqqUpmD9qQGoGOMdvLZ2Fnp/BcAAP//NLpw5j0LAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
