// Code generated by MockGen. DO NOT EDIT.
// Source: ./recipe_service_port.go
//
// Generated by this command:
//
//	mockgen -source=./recipe_service_port.go -destination=./mock/recipe_service_port_mock.go -package=port
//

// Package port is a generated GoMock package.
package port

import (
	context "context"
	reflect "reflect"

	entity "github.com/react/next-sample/backend/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockRecipeService is a mock of RecipeService interface.
type MockRecipeService struct {
	ctrl     *gomock.Controller
	recorder *MockRecipeServiceMockRecorder
	isgomock struct{}
}

// MockRecipeServiceMockRecorder is the mock recorder for MockRecipeService.
type MockRecipeServiceMockRecorder struct {
	mock *MockRecipeService
}

// NewMockRecipeService creates a new mock instance.
func NewMockRecipeService(ctrl *gomock.Controller) *MockRecipeService {
	mock := &MockRecipeService{ctrl: ctrl}
	mock.recorder = &MockRecipeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecipeService) EXPECT() *MockRecipeServiceMockRecorder {
	return m.recorder
}

// CreateRecipeTx mocks base method.
func (m *MockRecipeService) CreateRecipeTx(ctx context.Context, input *entity.Recipe) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRecipeTx", ctx, input)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRecipeTx indicates an expected call of CreateRecipeTx.
func (mr *MockRecipeServiceMockRecorder) CreateRecipeTx(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRecipeTx", reflect.TypeOf((*MockRecipeService)(nil).CreateRecipeTx), ctx, input)
}
