// Code generated by MockGen. DO NOT EDIT.
// Source: recipe_usecase_port.go
//
// Generated by this command:
//
//	mockgen -source=recipe_usecase_port.go -destination=./mock/recipe_usecase_port_mock.go -package=port
//

// Package port is a generated GoMock package.
package port

import (
	context "context"
	reflect "reflect"

	dto "github.com/react/next-sample/backend/usecase/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockRecipeUsecase is a mock of RecipeUsecase interface.
type MockRecipeUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockRecipeUsecaseMockRecorder
	isgomock struct{}
}

// MockRecipeUsecaseMockRecorder is the mock recorder for MockRecipeUsecase.
type MockRecipeUsecaseMockRecorder struct {
	mock *MockRecipeUsecase
}

// NewMockRecipeUsecase creates a new mock instance.
func NewMockRecipeUsecase(ctrl *gomock.Controller) *MockRecipeUsecase {
	mock := &MockRecipeUsecase{ctrl: ctrl}
	mock.recorder = &MockRecipeUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecipeUsecase) EXPECT() *MockRecipeUsecaseMockRecorder {
	return m.recorder
}

// AddRecipe mocks base method.
func (m *MockRecipeUsecase) AddRecipe(ctx context.Context, recipe *dto.Recipe) (*dto.Recipe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRecipe", ctx, recipe)
	ret0, _ := ret[0].(*dto.Recipe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddRecipe indicates an expected call of AddRecipe.
func (mr *MockRecipeUsecaseMockRecorder) AddRecipe(ctx, recipe any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRecipe", reflect.TypeOf((*MockRecipeUsecase)(nil).AddRecipe), ctx, recipe)
}

// FindRecipe mocks base method.
func (m *MockRecipeUsecase) FindRecipe(ctx context.Context, id int64) (*dto.Recipe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRecipe", ctx, id)
	ret0, _ := ret[0].(*dto.Recipe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRecipe indicates an expected call of FindRecipe.
func (mr *MockRecipeUsecaseMockRecorder) FindRecipe(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRecipe", reflect.TypeOf((*MockRecipeUsecase)(nil).FindRecipe), ctx, id)
}

// GetRecipeList mocks base method.
func (m *MockRecipeUsecase) GetRecipeList(ctx context.Context, page int64) ([]*dto.Recipe, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecipeList", ctx, page)
	ret0, _ := ret[0].([]*dto.Recipe)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRecipeList indicates an expected call of GetRecipeList.
func (mr *MockRecipeUsecaseMockRecorder) GetRecipeList(ctx, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecipeList", reflect.TypeOf((*MockRecipeUsecase)(nil).GetRecipeList), ctx, page)
}

// SearchRecipeList mocks base method.
func (m *MockRecipeUsecase) SearchRecipeList(ctx context.Context, word string, page int64) ([]*dto.Recipe, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchRecipeList", ctx, word, page)
	ret0, _ := ret[0].([]*dto.Recipe)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchRecipeList indicates an expected call of SearchRecipeList.
func (mr *MockRecipeUsecaseMockRecorder) SearchRecipeList(ctx, word, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchRecipeList", reflect.TypeOf((*MockRecipeUsecase)(nil).SearchRecipeList), ctx, word, page)
}
