apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: app
  name: app-pod
  namespace: ex
  selfLink: /apis/extensions/v1beta1/namespaces/ex/deployments/app-deploy
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels: # ラベルをKV型で設定
        app: app
    spec:
      containers:
      - image: gcr.io/app-labo-02/exsrc:latest
        imagePullPolicy: Always
        name: app-pod
        ports:
        - containerPort: 3001
          protocol: TCP
        resources:
          limits:
            cpu: 200m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
          - name: EX_REDIS_SERVER
            valueFrom:
              configMapKeyRef:
                name: user-main-config
                key: ex.redis-server
          - name: EX_REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: user-main-config
                key: ex.redis-server
          - name: EX_MYSQL_SERVER
            valueFrom:
              configMapKeyRef:
                name: user-main-config
                key: ex.mysql-server
          - name: EX_MYSQL_PASS
            valueFrom:
              configMapKeyRef:
                name: user-main-config
                key: ex.mysql-pass
          - name: EX_MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: user-main-config
                key: ex.mysql-database
          - name: EX_MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: user-main-config
                key: ex.mysql-user
          - name: EX_APP_DOMAIN
            valueFrom:
              configMapKeyRef:
                name: user-main-config
                key: ex.app-server
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}