// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/react/next-sample/backend/adapter/controller"
	"github.com/react/next-sample/backend/adapter/repositories"
	"github.com/react/next-sample/backend/domain/service"
	"github.com/react/next-sample/backend/infrastructure/db"
	"github.com/react/next-sample/backend/usecase"
)

// Injectors from wire.go:

func InitializeServer() *controller.Server {
	bunDB := db.NewDB()
	recipeRepository := repositories.NewRecipeRepository(bunDB)
	txRepository := db.NewTxRepository(bunDB)
	recipeMaterialRepository := repositories.NewRecipeMaterialRepository(bunDB)
	recipeService := service.NewRecipeService(txRepository, recipeRepository, recipeMaterialRepository)
	recipeUsecase := usecase.NewRecipeUsecase(recipeRepository, recipeService)
	recipeMaterialUsecase := usecase.NewRecipeMaterialUsecase(recipeMaterialRepository)
	server := controller.NewServer(bunDB, recipeUsecase, recipeMaterialUsecase, recipeService)
	return server
}

// wire.go:

var BunDBSet = wire.NewSet(db.NewDB)
