services:
  front:
    build:
      args:
        - NODE_VER=20.10.0
      context: ./
      dockerfile: Dockerfile
    container_name: react-app
    tty: true
    volumes:
      - ./app:/usr/src/app
    command: 'yarn dev'
    ports:
      - "8000:3000"
