// Code generated by MockGen. DO NOT EDIT.
// Source: ./recipe_material_repository.go
//
// Generated by this command:
//
//	mockgen -source=./recipe_material_repository.go -destination=./mock/recipe_material_repository_mock.go -package=repositories
//

// Package repositories is a generated GoMock package.
package repositories

import (
	context "context"
	reflect "reflect"

	entity "github.com/react/next-sample/backend/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockRecipeMaterialRepository is a mock of RecipeMaterialRepository interface.
type MockRecipeMaterialRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRecipeMaterialRepositoryMockRecorder
	isgomock struct{}
}

// MockRecipeMaterialRepositoryMockRecorder is the mock recorder for MockRecipeMaterialRepository.
type MockRecipeMaterialRepositoryMockRecorder struct {
	mock *MockRecipeMaterialRepository
}

// NewMockRecipeMaterialRepository creates a new mock instance.
func NewMockRecipeMaterialRepository(ctrl *gomock.Controller) *MockRecipeMaterialRepository {
	mock := &MockRecipeMaterialRepository{ctrl: ctrl}
	mock.recorder = &MockRecipeMaterialRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecipeMaterialRepository) EXPECT() *MockRecipeMaterialRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRecipeMaterialRepository) Create(ctx context.Context, recipe *entity.RecipeMaterial) (*entity.RecipeMaterial, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, recipe)
	ret0, _ := ret[0].(*entity.RecipeMaterial)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRecipeMaterialRepositoryMockRecorder) Create(ctx, recipe any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRecipeMaterialRepository)(nil).Create), ctx, recipe)
}

// Get mocks base method.
func (m *MockRecipeMaterialRepository) Get(ctx context.Context, id int64) (*entity.RecipeMaterial, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*entity.RecipeMaterial)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRecipeMaterialRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRecipeMaterialRepository)(nil).Get), ctx, id)
}
