apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: ex
  labels:
    app: app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3001
  selector:
    app: app
  type: LoadBalancer
