apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: ex
  labels:
    app: mysql
    role: master
    tier: backend
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
    role: master
    tier: backend